spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: true

logging:
  slack:
    webhook-uri: ${AWS_SM_SLACK_WEBHOOK_URL}
  config: classpath:logback-slack.xml
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

logging.slack.webhook-uri: https://hooks.slack.com/services/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
logging.slack.config: classpath:logback-slack.xml

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false